version: '3.5'

services:
  base: &base
    build:
      context: .

  api:
    <<: *base
    volumes:
      - '.:/opt/cop-js-todo-example'
      - '/opt/cop-js-todo-example/node_modules'
    ports:
      - '3000:3000'
